// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlaacimqfvknrpywmock.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYWFjaW1xZnZrbnJweXdtb2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjkxMDUsImV4cCI6MjA3MTIwNTEwNX0.MQ1XhcbysS2FaZ3DDcGldzEsibhhNQgMR5F_gwsxYww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});